import dspy
import pandas as pd

# Load the product entity resolution training data
train_df = pd.read_csv('data/train_products.csv')

def format_product(row, prefix):
    name = row[f'name_{prefix}'] if f'name_{prefix}' in row else ''
    description = row[f'description_{prefix}'] if f'description_{prefix}' in row else ''
    manufacturer = row[f'manufacturer_{prefix}'] if f'manufacturer_{prefix}' in row else ''
    price = row[f'price_{prefix}'] if f'price_{prefix}' in row else ''
    if prefix == 'abt':
        return f"Name: {name} Description: {description} Price: {price}"
    else:
        return f"Name: {name} Description: {description} Manufacturer: {manufacturer} Price: {price}"

# Create dspy.Example objects for each row
train_data = [
    dspy.Example(
        product1=format_product(row, 'abt'),
        product2=format_product(row, 'buy'),
        explanation="",  # Explanation will be generated by the model
        label=row['label']
    ).with_inputs("product1", "product2")
    for _, row in train_df.iterrows()
] 